In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [ ]:
# Loading data into numpy arrays
inp_paras = np.load('data/inp_paras_995.npy')
aoas_opt = np.load('data/aoas_opt_995.npy')
airfoils_opt = np.load('data/airfoils_opt_995.npy')

# Train Dataset - Inverse Design Parameters
print(inp_paras)
print(inp_paras.shape)

[[5.0000000e-01 1.9037683e+07 1.0300000e+00]
 [2.8000000e-01 8.9729841e+07 1.3800000e+00]
 [2.9000000e-01 6.1590231e+07 1.1800000e+00]
 ...
 [4.9000000e-01 7.1172774e+07 1.2100000e+00]
 [3.5000000e-01 5.6085562e+07 9.1000000e-01]
 [3.3000000e-01 5.2319263e+07 9.2000000e-01]]
(995, 3)


In [ ]:
# Train Dataset - optimal geometries ?
print(aoas_opt)
print(aoas_opt.shape)

[ 3.24710151e+00  7.11680430e+00  5.52304214e+00  5.47717159e+00
  4.98193061e+00  5.72120630e+00  3.21654399e+00  2.92190734e-01
  7.62762707e-01  4.58914579e+00  6.50760508e+00  3.79125939e+00
  5.54220236e+00  4.35139540e+00  4.95565185e+00  3.49101168e+00
  3.24093849e+00 -1.28986498e+00  5.96757653e+00  2.14311748e+00
  5.60730829e+00  6.59099423e+00  9.48778440e-01  2.42813964e+00
  2.54560053e+00  1.61739961e+00  4.40675158e+00  2.31380707e+00
  1.05763885e+00  9.22906608e-01  4.11223348e+00  1.09369156e+00
  3.73842874e+00  6.47467607e-01  4.34980961e+00  3.43867382e+00
  1.92646257e+00  5.56431847e+00  4.12619185e+00  3.75901260e+00
  6.63135374e+00  1.31929468e+00  2.36973319e+00  3.24101701e+00
  4.50091539e+00  5.36427412e+00  2.92484014e+00  5.50615162e+00
 -1.81329050e-01  1.63205482e+00  4.60697813e+00  2.47230345e+00
  2.34302145e+00  3.20825731e+00  1.91678020e+00  1.60143269e+00
  2.31066021e+00  3.46599685e-01  3.08083836e+00  8.04806430e+00
  2.25799481e+00  3.37363

In [ ]:
# Testing Dataset ?
print(airfoils_opt)
print(airfoils_opt.shape)

[[[ 9.99297000e-01  1.90699878e-03]
  [ 9.84541000e-01  7.45747310e-03]
  [ 9.78442000e-01  9.58867502e-03]
  ...
  [ 9.96793000e-01 -2.70626326e-03]
  [ 9.99863000e-01 -2.78600002e-03]
  [ 1.00000000e+00  1.58300000e-03]]

 [[ 9.99297000e-01  1.90700014e-03]
  [ 9.84541000e-01  7.46693676e-03]
  [ 9.78442000e-01  9.60892009e-03]
  ...
  [ 9.96793000e-01 -2.70602022e-03]
  [ 9.99863000e-01 -2.78600000e-03]
  [ 1.00000000e+00  1.58300000e-03]]

 [[ 9.99297000e-01  1.90700003e-03]
  [ 9.84541000e-01  7.46620000e-03]
  [ 9.78442000e-01  9.60742960e-03]
  ...
  [ 9.96793000e-01 -2.70600028e-03]
  [ 9.99863000e-01 -2.78600000e-03]
  [ 1.00000000e+00  1.58300000e-03]]

 ...

 [[ 9.99297000e-01  1.90699909e-03]
  [ 9.84541000e-01  7.45956876e-03]
  [ 9.78442000e-01  9.59315052e-03]
  ...
  [ 9.96793000e-01 -2.70625183e-03]
  [ 9.99863000e-01 -2.78600002e-03]
  [ 1.00000000e+00  1.58300000e-03]]

 [[ 9.99297000e-01  1.90699909e-03]
  [ 9.84541000e-01  7.45960466e-03]
  [ 9.78442000e-01  9.5932